<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <AssemblyName>setup</AssemblyName>
    <RootNamespace>Launcher</RootNamespace>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <SupportedOSPlatformVersion>6.1</SupportedOSPlatformVersion>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\Product.msi">
      <LogicalName>Product.msi</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>
